apiVersion: v1
data:
  apiToken: 
  dataIngestToken: 
kind: Secret
metadata:
  name: eks-k8s-2026-07-13
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
type: Opaque
---
apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: eks-k8s-2026-07-13
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://igp91846.live.dynatrace.com/api
  tokens: eks-k8s-2026-07-13
  activeGate:
    image: public.ecr.aws/dynatrace/dynatrace-activegate:1.341.31.20260701-034152
    nodeSelector:
      kubernetes.io/arch: arm64
      kubernetes.io/os: linux
    capabilities:
      - kubernetes-monitoring
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    replicas: 1
  kspm:
    mappedHostPaths:
      - /boot
      - /etc
      - /proc/sys/kernel
      - /sys/fs
      - /sys/kernel/security/apparmor
      - /usr/lib/systemd/system
      - /var/lib
  templates:
    kspmNodeConfigurationCollector:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-k8s-node-config-collector
        tag: 1.5.12
---
apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: eks-k8s-2026-07-13-agents
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://igp91846.live.dynatrace.com/api
  tokens: eks-k8s-2026-07-13
  oneAgent:
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  activeGate:
    image: public.ecr.aws/dynatrace/dynatrace-activegate:1.341.31.20260701-034152
    nodeSelector:
      kubernetes.io/arch: arm64
      kubernetes.io/os: linux
    capabilities:
      - routing
      - debugging
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    replicas: 1
  templates:
    otelCollector:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-otel-collector
        tag: latest
  logMonitoring: {}
  telemetryIngest:
    protocols:
      - jaeger
      - otlp
      - statsd
      - zipkin
    serviceName: telemetry-ingest
