apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: api
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
  annotations:
    oneagent.dynatrace.com/inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        oneagent.dynatrace.com/inject: "true"
    spec:
      containers:
        - name: api
          image: wordsmith-api:local-20260713
          imagePullPolicy: Always
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: telemetry-ingest.dynatrace.svc.cluster.local:4317
          ports:
            - containerPort: 8080
              name: api