apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: web
  selector:
    app: web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        oneagent.dynatrace.com/inject: "true"
    spec:
      containers:
        - name: web
          image: wordsmith-web:local-20260713
          imagePullPolicy: Always
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: telemetry-ingest.dynatrace.svc.cluster.local:4317
          ports:
            - containerPort: 80
              name: web
